---
- name: Install web server and firewalld
  hosts: intranet
  become: true 
  tasks:
  
    - name: ensure latest package httpd and firewalld
      ansible.builtin.yum:
        name:
          - httpd
          - firewalld
        state: latest

    - name: firewalld enabled and running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes

    - name: firewalld permits http service
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: httpd enabled and running
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: copy index.html using inline content
      ansible.builtin.copy:
        content: "Welcome to the example.com intranet!\n"
        dest: /var/www/html/index.html

- name: TEST web server
  hosts: localhost
  become: no
  tasks:

    - name: Ensure response code return 200 is ok
      ansible.builtin.uri:
        url: http://node2
        method: GET
        return_content: true
        status_code: 200 

...
