- name: Add text to an existing file
  hosts: servers
  remote_user: automation
  become: false
  tasks:
  - name: Add a single line of text to a file
    ansible.builtin.lineinfile:
      path: /home/automation/users.txt
      line: This line was added by the lineinfile module.
      state: present
