---
- name: using templates
  hosts: webservers 
  user: automation
  become: true
  vars:
    system_owner: Sergio.Marquez 
  tasks:

    - name: Install template motd.j2
      ansible.builtin.template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
